# Generated by Django 3.2.11 on 2023-02-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='user',
        ),
        migrations.DeleteModel(
            name='Agente',
        ),
        migrations.DeleteModel(
            name='Beneficiario',
        ),
    ]
